name: test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.18.3-bullseye ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        run: go test -v -race -timeout=60s ./...
